### ISSUE TITLE
Fix buttons going out of view

### ISSUE THREAD

**Issue by MattBann** [Thunder2103/Algorithms-Visualiser#30]
Some buttons go over the edge of their container. Tested on Ubuntu:

![image](https://github.com/Thunder2103/Algorithms-Visualiser/assets/69541270/e111f68a-fa33-4b3f-a5e5-e4e31a9274b6)

**Comment by Thunder2103** [comment]
I'm pretty sure I fixed most of it. Linux just likes to make me suffer.
